/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminZonesRouteImport } from './routes/admin.zones'
import { Route as AdminTournamentsRouteImport } from './routes/admin.tournaments'
import { Route as AdminTeamsRouteImport } from './routes/admin.teams'
import { Route as AdminPolygonsRouteImport } from './routes/admin.polygons'
import { Route as AdminMinimapRouteImport } from './routes/admin.minimap'
import { Route as AdminMatchesRouteImport } from './routes/admin.matches'
import { Route as AdminMapsRouteImport } from './routes/admin.maps'
import { Route as AdminHsvRouteImport } from './routes/admin.hsv'
import { Route as AdminCameraRouteImport } from './routes/admin.camera'
import { Route as AdminTeamsTeamIdRouteImport } from './routes/admin.teams.$teamId'
import { Route as AdminMatchesMatchIdRouteImport } from './routes/admin.matches.$matchId'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminZonesRoute = AdminZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTournamentsRoute = AdminTournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeamsRoute = AdminTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPolygonsRoute = AdminPolygonsRouteImport.update({
  id: '/polygons',
  path: '/polygons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMinimapRoute = AdminMinimapRouteImport.update({
  id: '/minimap',
  path: '/minimap',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMatchesRoute = AdminMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMapsRoute = AdminMapsRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHsvRoute = AdminHsvRouteImport.update({
  id: '/hsv',
  path: '/hsv',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCameraRoute = AdminCameraRouteImport.update({
  id: '/camera',
  path: '/camera',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeamsTeamIdRoute = AdminTeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMatchesMatchIdRoute = AdminMatchesMatchIdRouteImport.update({
  id: '/matches/$matchId',
  path: '/matches/$matchId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/camera': typeof AdminCameraRoute
  '/admin/hsv': typeof AdminHsvRoute
  '/admin/maps': typeof AdminMapsRoute
  '/admin/matches': typeof AdminMatchesRoute
  '/admin/minimap': typeof AdminMinimapRoute
  '/admin/polygons': typeof AdminPolygonsRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/tournaments': typeof AdminTournamentsRoute
  '/admin/zones': typeof AdminZonesRoute
  '/admin/matches/$matchId': typeof AdminMatchesMatchIdRoute
  '/admin/teams/$teamId': typeof AdminTeamsTeamIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/camera': typeof AdminCameraRoute
  '/admin/hsv': typeof AdminHsvRoute
  '/admin/maps': typeof AdminMapsRoute
  '/admin/matches': typeof AdminMatchesRoute
  '/admin/minimap': typeof AdminMinimapRoute
  '/admin/polygons': typeof AdminPolygonsRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/tournaments': typeof AdminTournamentsRoute
  '/admin/zones': typeof AdminZonesRoute
  '/admin/matches/$matchId': typeof AdminMatchesMatchIdRoute
  '/admin/teams/$teamId': typeof AdminTeamsTeamIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/camera': typeof AdminCameraRoute
  '/admin/hsv': typeof AdminHsvRoute
  '/admin/maps': typeof AdminMapsRoute
  '/admin/matches': typeof AdminMatchesRoute
  '/admin/minimap': typeof AdminMinimapRoute
  '/admin/polygons': typeof AdminPolygonsRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/tournaments': typeof AdminTournamentsRoute
  '/admin/zones': typeof AdminZonesRoute
  '/admin/matches/$matchId': typeof AdminMatchesMatchIdRoute
  '/admin/teams/$teamId': typeof AdminTeamsTeamIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/camera'
    | '/admin/hsv'
    | '/admin/maps'
    | '/admin/matches'
    | '/admin/minimap'
    | '/admin/polygons'
    | '/admin/teams'
    | '/admin/tournaments'
    | '/admin/zones'
    | '/admin/matches/$matchId'
    | '/admin/teams/$teamId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/camera'
    | '/admin/hsv'
    | '/admin/maps'
    | '/admin/matches'
    | '/admin/minimap'
    | '/admin/polygons'
    | '/admin/teams'
    | '/admin/tournaments'
    | '/admin/zones'
    | '/admin/matches/$matchId'
    | '/admin/teams/$teamId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/camera'
    | '/admin/hsv'
    | '/admin/maps'
    | '/admin/matches'
    | '/admin/minimap'
    | '/admin/polygons'
    | '/admin/teams'
    | '/admin/tournaments'
    | '/admin/zones'
    | '/admin/matches/$matchId'
    | '/admin/teams/$teamId'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/zones': {
      id: '/admin/zones'
      path: '/zones'
      fullPath: '/admin/zones'
      preLoaderRoute: typeof AdminZonesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tournaments': {
      id: '/admin/tournaments'
      path: '/tournaments'
      fullPath: '/admin/tournaments'
      preLoaderRoute: typeof AdminTournamentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teams': {
      id: '/admin/teams'
      path: '/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AdminTeamsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/polygons': {
      id: '/admin/polygons'
      path: '/polygons'
      fullPath: '/admin/polygons'
      preLoaderRoute: typeof AdminPolygonsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/minimap': {
      id: '/admin/minimap'
      path: '/minimap'
      fullPath: '/admin/minimap'
      preLoaderRoute: typeof AdminMinimapRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/matches': {
      id: '/admin/matches'
      path: '/matches'
      fullPath: '/admin/matches'
      preLoaderRoute: typeof AdminMatchesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/maps': {
      id: '/admin/maps'
      path: '/maps'
      fullPath: '/admin/maps'
      preLoaderRoute: typeof AdminMapsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hsv': {
      id: '/admin/hsv'
      path: '/hsv'
      fullPath: '/admin/hsv'
      preLoaderRoute: typeof AdminHsvRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/camera': {
      id: '/admin/camera'
      path: '/camera'
      fullPath: '/admin/camera'
      preLoaderRoute: typeof AdminCameraRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/matches/$matchId': {
      id: '/admin/matches/$matchId'
      path: '/matches/$matchId'
      fullPath: '/admin/matches/$matchId'
      preLoaderRoute: typeof AdminMatchesMatchIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teams/$teamId': {
      id: '/admin/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/admin/teams/$teamId'
      preLoaderRoute: typeof AdminTeamsTeamIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCameraRoute: typeof AdminCameraRoute
  AdminHsvRoute: typeof AdminHsvRoute
  AdminMapsRoute: typeof AdminMapsRoute
  AdminMatchesRoute: typeof AdminMatchesRoute
  AdminMinimapRoute: typeof AdminMinimapRoute
  AdminPolygonsRoute: typeof AdminPolygonsRoute
  AdminTeamsRoute: typeof AdminTeamsRoute
  AdminTournamentsRoute: typeof AdminTournamentsRoute
  AdminZonesRoute: typeof AdminZonesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminMatchesMatchIdRoute: typeof AdminMatchesMatchIdRoute
  AdminTeamsTeamIdRoute: typeof AdminTeamsTeamIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCameraRoute: AdminCameraRoute,
  AdminHsvRoute: AdminHsvRoute,
  AdminMapsRoute: AdminMapsRoute,
  AdminMatchesRoute: AdminMatchesRoute,
  AdminMinimapRoute: AdminMinimapRoute,
  AdminPolygonsRoute: AdminPolygonsRoute,
  AdminTeamsRoute: AdminTeamsRoute,
  AdminTournamentsRoute: AdminTournamentsRoute,
  AdminZonesRoute: AdminZonesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminMatchesMatchIdRoute: AdminMatchesMatchIdRoute,
  AdminTeamsTeamIdRoute: AdminTeamsTeamIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
