/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Presentation2RouteImport } from './routes/presentation-2'
import { Route as PresentationRouteImport } from './routes/presentation'
import { Route as MapsRouteImport } from './routes/maps'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TeamsTeamIdRouteImport } from './routes/teams.$teamId'
import { Route as MatchesMatchIdRouteImport } from './routes/matches.$matchId'
import { Route as AdminZonesRouteImport } from './routes/admin.zones'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTournamentsRouteImport } from './routes/admin.tournaments'
import { Route as AdminTeamsRouteImport } from './routes/admin.teams'
import { Route as AdminSchemaRouteImport } from './routes/admin.schema'
import { Route as AdminProcessesRouteImport } from './routes/admin.processes'
import { Route as AdminPolygonsRouteImport } from './routes/admin.polygons'
import { Route as AdminMinimapRouteImport } from './routes/admin.minimap'
import { Route as AdminMatchesRouteImport } from './routes/admin.matches'
import { Route as AdminMapsRouteImport } from './routes/admin.maps'
import { Route as AdminHsvRouteImport } from './routes/admin.hsv'
import { Route as AdminDiagramsRouteImport } from './routes/admin.diagrams'
import { Route as AdminCameraRouteImport } from './routes/admin.camera'
import { Route as AdminTeamsTeamIdRouteImport } from './routes/admin.teams.$teamId'
import { Route as AdminMatchesMatchIdRouteImport } from './routes/admin.matches.$matchId'
import { Route as AdminMapsMapIdRouteImport } from './routes/admin.maps.$mapId'

const Presentation2Route = Presentation2RouteImport.update({
  id: '/presentation-2',
  path: '/presentation-2',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationRoute = PresentationRouteImport.update({
  id: '/presentation',
  path: '/presentation',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsRoute = MapsRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TeamsTeamIdRoute = TeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesMatchIdRoute = MatchesMatchIdRouteImport.update({
  id: '/matches/$matchId',
  path: '/matches/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminZonesRoute = AdminZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTournamentsRoute = AdminTournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeamsRoute = AdminTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSchemaRoute = AdminSchemaRouteImport.update({
  id: '/schema',
  path: '/schema',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProcessesRoute = AdminProcessesRouteImport.update({
  id: '/processes',
  path: '/processes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPolygonsRoute = AdminPolygonsRouteImport.update({
  id: '/polygons',
  path: '/polygons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMinimapRoute = AdminMinimapRouteImport.update({
  id: '/minimap',
  path: '/minimap',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMatchesRoute = AdminMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMapsRoute = AdminMapsRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHsvRoute = AdminHsvRouteImport.update({
  id: '/hsv',
  path: '/hsv',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiagramsRoute = AdminDiagramsRouteImport.update({
  id: '/diagrams',
  path: '/diagrams',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCameraRoute = AdminCameraRouteImport.update({
  id: '/camera',
  path: '/camera',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeamsTeamIdRoute = AdminTeamsTeamIdRouteImport.update({
  id: '/$teamId',
  path: '/$teamId',
  getParentRoute: () => AdminTeamsRoute,
} as any)
const AdminMatchesMatchIdRoute = AdminMatchesMatchIdRouteImport.update({
  id: '/$matchId',
  path: '/$matchId',
  getParentRoute: () => AdminMatchesRoute,
} as any)
const AdminMapsMapIdRoute = AdminMapsMapIdRouteImport.update({
  id: '/$mapId',
  path: '/$mapId',
  getParentRoute: () => AdminMapsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/maps': typeof MapsRoute
  '/presentation': typeof PresentationRoute
  '/presentation-2': typeof Presentation2Route
  '/admin/camera': typeof AdminCameraRoute
  '/admin/diagrams': typeof AdminDiagramsRoute
  '/admin/hsv': typeof AdminHsvRoute
  '/admin/maps': typeof AdminMapsRouteWithChildren
  '/admin/matches': typeof AdminMatchesRouteWithChildren
  '/admin/minimap': typeof AdminMinimapRoute
  '/admin/polygons': typeof AdminPolygonsRoute
  '/admin/processes': typeof AdminProcessesRoute
  '/admin/schema': typeof AdminSchemaRoute
  '/admin/teams': typeof AdminTeamsRouteWithChildren
  '/admin/tournaments': typeof AdminTournamentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/zones': typeof AdminZonesRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/maps/$mapId': typeof AdminMapsMapIdRoute
  '/admin/matches/$matchId': typeof AdminMatchesMatchIdRoute
  '/admin/teams/$teamId': typeof AdminTeamsTeamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/maps': typeof MapsRoute
  '/presentation': typeof PresentationRoute
  '/presentation-2': typeof Presentation2Route
  '/admin/camera': typeof AdminCameraRoute
  '/admin/diagrams': typeof AdminDiagramsRoute
  '/admin/hsv': typeof AdminHsvRoute
  '/admin/maps': typeof AdminMapsRouteWithChildren
  '/admin/matches': typeof AdminMatchesRouteWithChildren
  '/admin/minimap': typeof AdminMinimapRoute
  '/admin/polygons': typeof AdminPolygonsRoute
  '/admin/processes': typeof AdminProcessesRoute
  '/admin/schema': typeof AdminSchemaRoute
  '/admin/teams': typeof AdminTeamsRouteWithChildren
  '/admin/tournaments': typeof AdminTournamentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/zones': typeof AdminZonesRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/maps/$mapId': typeof AdminMapsMapIdRoute
  '/admin/matches/$matchId': typeof AdminMatchesMatchIdRoute
  '/admin/teams/$teamId': typeof AdminTeamsTeamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/maps': typeof MapsRoute
  '/presentation': typeof PresentationRoute
  '/presentation-2': typeof Presentation2Route
  '/admin/camera': typeof AdminCameraRoute
  '/admin/diagrams': typeof AdminDiagramsRoute
  '/admin/hsv': typeof AdminHsvRoute
  '/admin/maps': typeof AdminMapsRouteWithChildren
  '/admin/matches': typeof AdminMatchesRouteWithChildren
  '/admin/minimap': typeof AdminMinimapRoute
  '/admin/polygons': typeof AdminPolygonsRoute
  '/admin/processes': typeof AdminProcessesRoute
  '/admin/schema': typeof AdminSchemaRoute
  '/admin/teams': typeof AdminTeamsRouteWithChildren
  '/admin/tournaments': typeof AdminTournamentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/zones': typeof AdminZonesRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/maps/$mapId': typeof AdminMapsMapIdRoute
  '/admin/matches/$matchId': typeof AdminMatchesMatchIdRoute
  '/admin/teams/$teamId': typeof AdminTeamsTeamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/admin'
    | '/login'
    | '/maps'
    | '/presentation'
    | '/presentation-2'
    | '/admin/camera'
    | '/admin/diagrams'
    | '/admin/hsv'
    | '/admin/maps'
    | '/admin/matches'
    | '/admin/minimap'
    | '/admin/polygons'
    | '/admin/processes'
    | '/admin/schema'
    | '/admin/teams'
    | '/admin/tournaments'
    | '/admin/users'
    | '/admin/zones'
    | '/matches/$matchId'
    | '/teams/$teamId'
    | '/admin/'
    | '/admin/maps/$mapId'
    | '/admin/matches/$matchId'
    | '/admin/teams/$teamId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/login'
    | '/maps'
    | '/presentation'
    | '/presentation-2'
    | '/admin/camera'
    | '/admin/diagrams'
    | '/admin/hsv'
    | '/admin/maps'
    | '/admin/matches'
    | '/admin/minimap'
    | '/admin/polygons'
    | '/admin/processes'
    | '/admin/schema'
    | '/admin/teams'
    | '/admin/tournaments'
    | '/admin/users'
    | '/admin/zones'
    | '/matches/$matchId'
    | '/teams/$teamId'
    | '/admin'
    | '/admin/maps/$mapId'
    | '/admin/matches/$matchId'
    | '/admin/teams/$teamId'
  id:
    | '__root__'
    | '/'
    | '/accept-invite'
    | '/admin'
    | '/login'
    | '/maps'
    | '/presentation'
    | '/presentation-2'
    | '/admin/camera'
    | '/admin/diagrams'
    | '/admin/hsv'
    | '/admin/maps'
    | '/admin/matches'
    | '/admin/minimap'
    | '/admin/polygons'
    | '/admin/processes'
    | '/admin/schema'
    | '/admin/teams'
    | '/admin/tournaments'
    | '/admin/users'
    | '/admin/zones'
    | '/matches/$matchId'
    | '/teams/$teamId'
    | '/admin/'
    | '/admin/maps/$mapId'
    | '/admin/matches/$matchId'
    | '/admin/teams/$teamId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInviteRoute: typeof AcceptInviteRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  MapsRoute: typeof MapsRoute
  PresentationRoute: typeof PresentationRoute
  Presentation2Route: typeof Presentation2Route
  MatchesMatchIdRoute: typeof MatchesMatchIdRoute
  TeamsTeamIdRoute: typeof TeamsTeamIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/presentation-2': {
      id: '/presentation-2'
      path: '/presentation-2'
      fullPath: '/presentation-2'
      preLoaderRoute: typeof Presentation2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentation': {
      id: '/presentation'
      path: '/presentation'
      fullPath: '/presentation'
      preLoaderRoute: typeof PresentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps': {
      id: '/maps'
      path: '/maps'
      fullPath: '/maps'
      preLoaderRoute: typeof MapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/teams/$teamId': {
      id: '/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$matchId': {
      id: '/matches/$matchId'
      path: '/matches/$matchId'
      fullPath: '/matches/$matchId'
      preLoaderRoute: typeof MatchesMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/zones': {
      id: '/admin/zones'
      path: '/zones'
      fullPath: '/admin/zones'
      preLoaderRoute: typeof AdminZonesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tournaments': {
      id: '/admin/tournaments'
      path: '/tournaments'
      fullPath: '/admin/tournaments'
      preLoaderRoute: typeof AdminTournamentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teams': {
      id: '/admin/teams'
      path: '/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AdminTeamsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/schema': {
      id: '/admin/schema'
      path: '/schema'
      fullPath: '/admin/schema'
      preLoaderRoute: typeof AdminSchemaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/processes': {
      id: '/admin/processes'
      path: '/processes'
      fullPath: '/admin/processes'
      preLoaderRoute: typeof AdminProcessesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/polygons': {
      id: '/admin/polygons'
      path: '/polygons'
      fullPath: '/admin/polygons'
      preLoaderRoute: typeof AdminPolygonsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/minimap': {
      id: '/admin/minimap'
      path: '/minimap'
      fullPath: '/admin/minimap'
      preLoaderRoute: typeof AdminMinimapRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/matches': {
      id: '/admin/matches'
      path: '/matches'
      fullPath: '/admin/matches'
      preLoaderRoute: typeof AdminMatchesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/maps': {
      id: '/admin/maps'
      path: '/maps'
      fullPath: '/admin/maps'
      preLoaderRoute: typeof AdminMapsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hsv': {
      id: '/admin/hsv'
      path: '/hsv'
      fullPath: '/admin/hsv'
      preLoaderRoute: typeof AdminHsvRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/diagrams': {
      id: '/admin/diagrams'
      path: '/diagrams'
      fullPath: '/admin/diagrams'
      preLoaderRoute: typeof AdminDiagramsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/camera': {
      id: '/admin/camera'
      path: '/camera'
      fullPath: '/admin/camera'
      preLoaderRoute: typeof AdminCameraRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teams/$teamId': {
      id: '/admin/teams/$teamId'
      path: '/$teamId'
      fullPath: '/admin/teams/$teamId'
      preLoaderRoute: typeof AdminTeamsTeamIdRouteImport
      parentRoute: typeof AdminTeamsRoute
    }
    '/admin/matches/$matchId': {
      id: '/admin/matches/$matchId'
      path: '/$matchId'
      fullPath: '/admin/matches/$matchId'
      preLoaderRoute: typeof AdminMatchesMatchIdRouteImport
      parentRoute: typeof AdminMatchesRoute
    }
    '/admin/maps/$mapId': {
      id: '/admin/maps/$mapId'
      path: '/$mapId'
      fullPath: '/admin/maps/$mapId'
      preLoaderRoute: typeof AdminMapsMapIdRouteImport
      parentRoute: typeof AdminMapsRoute
    }
  }
}

interface AdminMapsRouteChildren {
  AdminMapsMapIdRoute: typeof AdminMapsMapIdRoute
}

const AdminMapsRouteChildren: AdminMapsRouteChildren = {
  AdminMapsMapIdRoute: AdminMapsMapIdRoute,
}

const AdminMapsRouteWithChildren = AdminMapsRoute._addFileChildren(
  AdminMapsRouteChildren,
)

interface AdminMatchesRouteChildren {
  AdminMatchesMatchIdRoute: typeof AdminMatchesMatchIdRoute
}

const AdminMatchesRouteChildren: AdminMatchesRouteChildren = {
  AdminMatchesMatchIdRoute: AdminMatchesMatchIdRoute,
}

const AdminMatchesRouteWithChildren = AdminMatchesRoute._addFileChildren(
  AdminMatchesRouteChildren,
)

interface AdminTeamsRouteChildren {
  AdminTeamsTeamIdRoute: typeof AdminTeamsTeamIdRoute
}

const AdminTeamsRouteChildren: AdminTeamsRouteChildren = {
  AdminTeamsTeamIdRoute: AdminTeamsTeamIdRoute,
}

const AdminTeamsRouteWithChildren = AdminTeamsRoute._addFileChildren(
  AdminTeamsRouteChildren,
)

interface AdminRouteChildren {
  AdminCameraRoute: typeof AdminCameraRoute
  AdminDiagramsRoute: typeof AdminDiagramsRoute
  AdminHsvRoute: typeof AdminHsvRoute
  AdminMapsRoute: typeof AdminMapsRouteWithChildren
  AdminMatchesRoute: typeof AdminMatchesRouteWithChildren
  AdminMinimapRoute: typeof AdminMinimapRoute
  AdminPolygonsRoute: typeof AdminPolygonsRoute
  AdminProcessesRoute: typeof AdminProcessesRoute
  AdminSchemaRoute: typeof AdminSchemaRoute
  AdminTeamsRoute: typeof AdminTeamsRouteWithChildren
  AdminTournamentsRoute: typeof AdminTournamentsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminZonesRoute: typeof AdminZonesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCameraRoute: AdminCameraRoute,
  AdminDiagramsRoute: AdminDiagramsRoute,
  AdminHsvRoute: AdminHsvRoute,
  AdminMapsRoute: AdminMapsRouteWithChildren,
  AdminMatchesRoute: AdminMatchesRouteWithChildren,
  AdminMinimapRoute: AdminMinimapRoute,
  AdminPolygonsRoute: AdminPolygonsRoute,
  AdminProcessesRoute: AdminProcessesRoute,
  AdminSchemaRoute: AdminSchemaRoute,
  AdminTeamsRoute: AdminTeamsRouteWithChildren,
  AdminTournamentsRoute: AdminTournamentsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminZonesRoute: AdminZonesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInviteRoute: AcceptInviteRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  MapsRoute: MapsRoute,
  PresentationRoute: PresentationRoute,
  Presentation2Route: Presentation2Route,
  MatchesMatchIdRoute: MatchesMatchIdRoute,
  TeamsTeamIdRoute: TeamsTeamIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
